Need to randomise the root_cell to a more cool location.
    Write an animate function that gets called each loop. if animate=True, process animation.
    
    randomise system_core.
    def update_lists(): # updates all the subsystems list.
    def animate():
        if animate == True:
            
            #recalculate all
            alpha = 
        else:
            return
    # Dirty methods.
    Keep adding node_cells, and if it exceeds the maximum neighbour limit, call the abandon_cells() method and pass all the node_cells. Make it void.
    
    subystems assignment comes after this crap
