import periodictable.core
def init(table, reload=False):
    if 'series' in table.properties and not reload: return
    table.properties.append('series')
    
    periodictable.core.Element.series = "Nonmetals"
    
    for name,series in data.items():
        el = table.symbol(name)
        el.series = series
            
data = dict(

    H = "Nonmetals",
    He = "Noble gases",
    Li = "Alkali metals",
    Be = "Alkaline earth metals",
    B = "Semimetals",
    
    C = "Nonmetals",
    N = "Nonmetals",
    O = "Nonmetals",
    
    F = "Halogens",
    Ne = "Noble gases",
    Na = "Alkali metals",
    Mg = "Alkaline earth metals",
    Al = "Post-transition metals",
    
    Si = "Semimetals",
    P = "Nonmetals",
    S = "Nonmetals",
    
    Cl = "Halogens",
    Ar = "Noble gases",
    K = "Alkali metals",
    Ca = "Alkaline earth metals",
    Sc = "Transition metals",
    Ti = "Transition metals",
    V = "Transition metals",
    Cr = "Transition metals",
    Mn = "Transition metals",
    Fe = "Transition metals",
    Co = "Transition metals",
    Ni = "Transition metals",
    Cu = "Transition metals",
    Zn = "Transition metals",
    Ga = "Post-transition metals",
    
    Ge = "Semimetals",
    As = "Semimetals",
    Se = "Nonmetals",
    
    Br = "Halogens",
    Kr = "Noble gases",
    Rb = "Alkali metals",
    Sr = "Alkaline earth metals",
    Y = "Transition metals",
    Zr = "Transition metals",
    Nb = "Transition metals",
    Mo = "Transition metals",
    Tc = "Transition metals",
    Ru = "Transition metals",
    Rh = "Transition metals",
    Pd = "Transition metals",
    Ag = "Transition metals",
    Cd = "Transition metals",
    In = "Post-transition metals",
    
    Sn = "Post-transition metals",
    Sb = "Semimetals",
    Te = "Semimetals",
    
    I = "Halogens",
    Xe = "Noble gases",
    Cs = "Alkali metals",
    Ba = "Alkaline earth metals",
    La = "Lanthanides",
    Ce = "Lanthanides",
    Pr = "Lanthanides",
    Nd = "Lanthanides",
    Pm = "Lanthanides",
    Sm = "Lanthanides",
    Eu = "Lanthanides",
    Gd = "Lanthanides",
    Tb = "Lanthanides",
    Dy = "Lanthanides",
    Ho = "Lanthanides",
    Er = "Lanthanides",
    Tm = "Lanthanides",
    Yb = "Lanthanides",
    Lu = "Lanthanides",
    Hf = "Transition metals",
    Ta = "Transition metals",
    W = "Transition metals",
    Re = "Transition metals",
    Os = "Transition metals",
    Ir = "Transition metals",
    Pt = "Transition metals",
    Au = "Transition metals",
    Hg = "Transition metals",
    Tl = "Post-transition metals",
    
    Pb = "Post-transition metals",
    Bi = "Post-transition metals",
    Po = "Semimetals",
    
    At = "Halogens",
    Rn = "Noble gases",
    Fr = "Alkali metals",
    Ra = "Alkaline earth metals",
    Ac = "Actinides",
    Th = "Actinides",
    Pa = "Actinides",
    U = "Actinides",
    Np = "Actinides",
    Pu = "Actinides",
    Am = "Actinides",
    Cm = "Actinides",
    Bk = "Actinides",
    Cf = "Actinides",
    Es = "Actinides",
    Fm = "Actinides",
    Md = "Actinides",
    No = "Actinides",
    Lr = "Actinides",
    Rf = "Transition metals",
    Db = "Transition metals",
    Sg = "Transition metals",
    Bh = "Transition metals",
    Hs = "Transition metals",
    Mt = "Transition metals",
    Ds = "Transition metals",
    Rg = "Transition metals",
    Cn = "Transition metals",
    Nh = "Post-transition metals",
    Fl = "Post-transition metals",
    Mc = "Post-transition metals",
    Lv = "Post-transition metals",
    Ts = "Halogens",
    Og = "Noble gases",
)

init(periodictable.elements)
